version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_hospital
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./schema:/schema
    networks:
      - manager_hospital_network

  container_patient:
    build: 
      context: ./backend/patient
    container_name: container_patient
    entrypoint: wait-for db:5432 -t 40 -- npx nodemon src/main.ts
    tty: true 
    volumes:
      - ./backend/patient:/usr/src/app
    depends_on:
      - db 
    networks:
      - manager_hospital_network

  container_doctor:
    build: 
      context: ./backend/doctor 
    container_name: container_doctor
    entrypoint: wait-for db:5432 -t 40 -- npx nodemon src/main.ts
    tty: true
    volumes:
      - ./backend/doctor:/usr/src/app
    depends_on:
      - db
    networks:
      - manager_hospital_network

  nginx:
    build: 
      context: ./nginx
    container_name: nginx_manager_hospital 
    tty: true 
    ports:
      - 3001:80
    networks:
      - manager_hospital_network
    depends_on:
      - db
      - container_patient
      - container_doctor

networks:
  manager_hospital_network:
    driver: bridge
